### ISSUE TITLE
Does the docker container have all modules?

### ISSUE THREAD

**Issue by kbalint** [dlt-rilmta/emtsv#15]
Hello, I've downloaded **all** previous (< :latest) docker containers and tried the rest api with the following sentence: "Budapest szép város."

The modules represented as urls I've tried:

1. url: http://127.0.0.1:5000/tok-morph (which if I understand correctly equals http://127.0.0.1:5000/tok/morph)
response: 
```
form	wsafter	anas
Budapest	" "	[{"lemma": "Budapest", "tag": "[/N][Nom]", "morphana": "Budapest[/N]=Budapest+[Nom]=", "readable": "Budapest[/N] + [Nom]", "twolevel": "B:B u:u d:d a:a p:p e:e s:s t:t :[/N] :[Nom]"}]
szép	" "	[{"lemma": "szép", "tag": "[/Adj][Nom]", "morphana": "szép[/Adj]=szép+[Nom]=", "readable": "szép[/Adj] + [Nom]", "twolevel": "s:s z:z é:é p:p :[/Adj] :[Nom]"}, {"lemma": "szép", "tag": "[/Adv|AdjMod]", "morphana": "szép[/Adv|AdjMod]=szép", "readable": "szép[/Adv|AdjMod]", "twolevel": "s:s z:z é:é p:p :[/Adv|AdjMod]"}]
város	""	[{"lemma": "város", "tag": "[/N][Nom]", "morphana": "város[/N]=város+[Nom]=", "readable": "város[/N] + [Nom]", "twolevel": "v:v á:á r:r o:o s:s :[/N] :[Nom]"}]
.	[{"lemma": ".", "tag": "[Punct]", "morphana": "", "readable": "", "twolevel": ""}]

```
2. url: http://127.0.0.1:5000/analyze (eg. /tok/morph/pos/chunk/ner/conv-morph/.... ? )
resp: 
`form	wsafter	anas	lemma	xpostag	NP-BIO	upostag	feats	id	deprel	head	cons`

3. url: http://127.0.0.1:5000/tok-pos
resp: `form	wsafter	anas	lemma	xpostag`

4. url: http://127.0.0.1:5000/tok-chunk
resp: `form	wsafter	anas	lemma	xpostag	NP-BIO`

Am I missing some parameters or does the docker container require something more to work? Thanks!

**Comment by dlazesz** [comment]
What does the logs say?

The details on the presets are here:

- https://github.com/dlt-rilmta/emtsv#modules ("The following presets are defined as shorthands for the common tasks:")
- https://github.com/dlt-rilmta/emtsv/blob/master/config.py#L184

If there is an error during the processing it yields an exception which can be seen in the logs. Therefore no text after the header is written. This is a known bug and will be fixed in some later version of xtsv.

Why don't you build a docker image from the latest sources?

**Comment by kbalint** [comment]
@dlazesz here's the console output for http://127.0.0.1:5000/tok/morph/pos, text='Budapest szép város.'

```
$ docker run --rm -p5000:5000 -it mtaril/emtsv:4.0.4
[uWSGI] getting INI configuration from /app/docker/uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue Dec 29 10:22:48 2020] ***
compiled with version: 8.3.0 on 05 May 2020 14:13:36
os: Linux-5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
nodename: 7fb25b46a949
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 6
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
setgid() to 107
setuid() to 105
chdir() to /app
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:5000 fd 3
Python version: 3.8.2 (default, Feb 26 2020, 14:58:38)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55924d224170
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 329352 bytes (321 KB) for 2 cores
*** Operational MODE: preforking ***
added /app/ to pythonpath.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6)
spawned uWSGI worker 1 (pid: 7, cores: 1)
spawned uWSGI worker 2 (pid: 8, cores: 1)
mapping worker 1 to CPUs: 0
mapping worker 2 to CPUs: 1
mounting docker/emtsvREST.wsgi on /
mounting docker/emtsvREST.wsgi on /
/usr/local/lib/python3.8/site-packages/npyscreen/proto_fm_screen_area.py:150: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.show_from_y is 0 and \
/usr/local/lib/python3.8/site-packages/npyscreen/proto_fm_screen_area.py:150: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.show_from_y is 0 and \
/usr/local/lib/python3.8/site-packages/npyscreen/proto_fm_screen_area.py:151: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.show_from_x is 0 and \
/usr/local/lib/python3.8/site-packages/npyscreen/proto_fm_screen_area.py:151: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.show_from_x is 0 and \
/usr/local/lib/python3.8/site-packages/npyscreen/npyspmfuncs.py:29: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if rtn is not 0: return False
/usr/local/lib/python3.8/site-packages/npyscreen/npyspmfuncs.py:29: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if rtn is not 0: return False
/usr/local/lib/python3.8/site-packages/npyscreen/wgmultiline.py:476: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.values[counter].find(searchingfor) is not -1:
/usr/local/lib/python3.8/site-packages/npyscreen/wgmultiline.py:476: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.values[counter].find(searchingfor) is not -1:
/usr/local/lib/python3.8/site-packages/npyscreen/wgautocomplete.py:61: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(possibilities) is 0:
/usr/local/lib/python3.8/site-packages/npyscreen/wgautocomplete.py:66: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(possibilities) is 1:
/usr/local/lib/python3.8/site-packages/npyscreen/wgautocomplete.py:61: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(possibilities) is 0:
/usr/local/lib/python3.8/site-packages/npyscreen/wgautocomplete.py:66: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(possibilities) is 1:
/usr/local/lib/python3.8/site-packages/npyscreen/wgcombobox.py:15: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if value is 0:
/usr/local/lib/python3.8/site-packages/npyscreen/wgcombobox.py:29: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.value == None or self.value is '':
/usr/local/lib/python3.8/site-packages/npyscreen/wgcombobox.py:15: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if value is 0:
/usr/local/lib/python3.8/site-packages/npyscreen/wgcombobox.py:29: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.value == None or self.value is '':
/usr/local/lib/python3.8/site-packages/npyscreen/wgmonthbox.py:224: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if thisday is 0:
/usr/local/lib/python3.8/site-packages/npyscreen/wgmonthbox.py:224: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if thisday is 0:
WSGI app 0 (mountpoint='/') ready in 1 seconds on interpreter 0x55924d224170 pid: 7 (default app)
WSGI app 0 (mountpoint='/') ready in 1 seconds on interpreter 0x55924d224170 pid: 8 (default app)
/usr/local/lib/python3.8/site-packages/scipy/optimize/_shgo.py:495: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if cons['type'] is 'ineq':
/usr/local/lib/python3.8/site-packages/scipy/optimize/_shgo.py:743: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(self.X_min) is not 0:
**No blank line before EOF (no filename for stream)!**
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/xtsv/tsvhandler.py", line 67, in process
    yield from ('{0}\n'.format('\t'.join(tok)) for tok in internal_app.process_sentence(sen, field_values))
  File "/app/purepospy/purepospy/purepospy.py", line 183, in process_sentence
    m[pos] = [(ana['lemma'], ana['tag']) for ana in json_loads(tok[field_indices[1]])]  # lemma, tag
**IndexError: list index out of range**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 162, in generator
    for item in gen:
  File "/usr/local/lib/python3.8/site-packages/xtsv/pipeline.py", line 494, in <genexpr>
    response = Response(stream_with_context(final_convert((line.encode('UTF-8') for line in last_prog))),
  File "/usr/local/lib/python3.8/site-packages/xtsv/tsvhandler.py", line 70, in process
    raise type(e)('In "{0}" at {1}: {2}'.format(track_stream['file_name'], curr_line, str(e))).\
  File "/usr/local/lib/python3.8/site-packages/xtsv/tsvhandler.py", line 67, in process
    yield from ('{0}\n'.format('\t'.join(tok)) for tok in internal_app.process_sentence(sen, field_values))
  File "/app/purepospy/purepospy/purepospy.py", line 183, in process_sentence
    m[pos] = [(ana['lemma'], ana['tag']) for ana in json_loads(tok[field_indices[1]])]  # lemma, tag
IndexError: In "no filename for stream" at 6: list index out of range
[pid: 7|app: 0|req: 1/1] 172.17.0.1 () {32 vars in 493 bytes} [Tue Dec 29 10:23:00 2020] POST /tok/morph/pos => generated 32 bytes in 2217 msecs (HTTP/1.1 200) 2 headers in 114 bytes (1 switches on core 0)
```
I can read the exception, but have no toolset knowledge to resolve this.

I **might** be able to build a docker image from source, but how would one expect a humanities undergrad to do so?...

**Comment by dlazesz** [comment]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/xtsv/tsvhandler.py", line 67, in process
>     yield from ('{0}\n'.format('\t'.join(tok)) for tok in internal_app.process_sentence(sen, field_values))
>   File "/app/purepospy/purepospy/purepospy.py", line 183, in process_sentence
>     m[pos] = [(ana['lemma'], ana['tag']) for ana in json_loads(tok[field_indices[1]])]  # lemma, tag
> **IndexError: list index out of range**

IndexError in PurePOS. This is a known bug, fixed in 9422a4794cc2b8f64f2a830a970f8c968ff229cc . The latest sources does not have this bug. To workaround it, please add an empty line at the end of the input.

> I can read the exception, but have no toolset knowledge to resolve this.

Next time you might put it in the OP without asing in conjunction with the used emtsv version identification.

> I **might** be able to build a docker image from source, but how would one expect a humanities undergrad to do so?...

Excerpts from the GPL license:

> THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY OF ANY KIND

and

> SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

There is no free lunch. I **might** expect the hordes of humanities undergrad students eager to use emtsv to use the web service (http://e-magyar.hu/hu/parser) and do not bother with docker stuff if I were to expect anything from anyone.

BTW building the docker from source does not require any special extra skills compared to running the docker container and use the REST API. It takes just a single `docker build .` command after the cloning and there is documentation on it: https://github.com/dlt-rilmta/emtsv/blob/master/docs/installation.md

I close this issue, as the PurePOS related bug is already fixed. Waiting for new release, which is tracked in #13 .

**Comment by kbalint** [comment]
@dlazesz : 

1) huge thanks! version 4.0.4 started working with the addition of a trailing \r\n . 
If the example codes / documentation could state this, that would solve all non-technical errors I guess.
This means all former docker images are working as expected! :)

2) I would LOVE to use e-magyar as a public REST API. Is it possible? 
[Last time I checked](https://github.com/dlt-rilmta/e-magyar.hu/issues/3), it had some hickups, and [I could not get through](https://github.com/dlt-rilmta/e-magyar.hu/issues/2) to ask about it :)

3) I understand that this github project is under GPL licence, but by hosting this project under an Academy Institute's github account, it means that it is at least is some parts taxpayer funded, right?

**Comment by dlazesz** [comment]
> @dlazesz :
> 
> 1. huge thanks! version 4.0.4 started working with the addition of a trailing \r\n .
>    If the example codes / documentation could state this, that would solve all non-technical errors I guess.
>    This means all former docker images are working as expected! :)

Cheers! :)

[The troubleshooting section](https://github.com/dlt-rilmta/emtsv/blob/master/docs/troubleshooting.md#errors-like-the-one-below-appear-if-quntoken-version-is-317-and-emtsv-version-is-406) has been updated ( 3fc9a78d8f855b7d574b210c13330b9f519b37fc ). Now, with hand on your heart, do you swear that you have checked that page throughtly before opening an issue? Because if not, there is no benefit in amending that section.

> 2. I would LOVE to use e-magyar as a public REST API. Is it possible?
>    [Last time I checked](https://github.com/dlt-rilmta/e-magyar.hu/issues/3), it had some hickups, and [I could not get through](https://github.com/dlt-rilmta/e-magyar.hu/issues/2) to ask about it :)

The e-magyar.hu is dreadfully outdated, because the project has ended. There are efforts to at least [update the backend to emtsv](https://github.com/dlt-rilmta/e-magyar.hu/tree/minimal_transition_to_emtsv), so the update should happen soon as gratis.

As the high amount of resources needed to operate such service without explicit income or dedicated resources there will be no open API endpoint in the foreseeable future. (RIL is not Google.) There were some "public" API endpoint, but currently every single one that I am aware of is down or have outdated version of e-magyar.

Please forward your inquiry to @tamvar as he is the CEO.

> 3. I understand that this github project is under GPL licence, but by hosting this project under an Academy Institute's github account, it means that it is at least is some parts taxpayer funded, right?

As of the GPL anybody can use or host e-magyar without asking permission. I do not do maintenance and support anymore (as of dec 31.). Funding, release and website issues have never been my part of e-magyar/emtsv. As far as I know, taxpayers founded the development not the hosting costs of an open API forever at any required scale. If you wish to contribute with some money or resources to the hosting I think @tamvar will be listening.

I also have some ideas what **should have** taxpayers founded instead of the current things. Therefore I will continue to add features to emtsv as an outside collaborator (from an other institution and project founded by taxpayers) in order to conduct my research, but everything else is on the mercy of whoever have the intention and the resources to maintain support and host this software as in GPL.
