### ISSUE TITLE
emtsv returns empty lemmas for some tokens

### ISSUE THREAD

**Issue by DavidNemeskey** [dlt-rilmta/emtsv#7]
I am not entirely sure which component is to blame (the educated guess is emLem). For an example, run the sentence
```
A Kispesti Önkormányzat kezdeményezésére – a Budapest Főváros Közigazgatási Hivatala Fővárosi Gyámhivatala – a Gyvt.
```
through the pipeline (and yes, this is not a full sentence, but quntoken thinks it is). The resulting analysis (see [no_lemma.tsv.txt](https://github.com/dlt-rilmta/emtsv/files/3526321/no_lemma.tsv.txt)) has no lemmas for the emdash characters (`–`). Note that other punctuation marks, such as the dot (`.`) _does_ have a lemma (itself).

As you can see from the statistics ([no_lemma_stats.tsv.txt](https://github.com/dlt-rilmta/emtsv/files/3526343/no_lemma_stats.tsv.txt)), the tokens most affected by this bug are the emdash and the slash. The rest are mostly inflectional / derivational suffixes erroneously separated from the stem (which could probably also be salvaged somehow, but hardly worth the effort).

**Comment by dlazesz** [comment]
Dash fixed in 6c3dc4cd25a54f76b245d9d34b6dbbe09e5dac8f

From your list only the following have anything to do with emLem:
- ugyanegy
- /
- ns
- Ns
- NS
- ns-mal
- (rám)
- +hozzá

We will investigate these.

The others yield no output from emMorph and fully handled by the guesser. IMO correctly.

**Comment by dlazesz** [comment]
News:
I have traced down and fixed a bug in emMorphPy [see commit](https://github.com/dlt-rilmta/emmorphpy/commit/4d08f4b453bc6ba843781ada34588a5ede895bef)

The current status is the following:

```
–	–[Hyph:Dash]=–	–	[Hyph:Dash]

/	/[Hyph:Slash]=/	/	[Hyph:Slash]

ugyanegy	ugyanegy[/Adj|Pred|Pro]=ugyanegy+[Nom]=		[/Adj|Pred|Pro][Nom]
ugyanegy	ugyanegy[/Det|Art.NDef]=ugyanegy	ugyanegy	[/Det|Art.NDef]

ns	ns[/N|Abbr|Unit]=ns+[Nom]=		[/N|Abbr|Unit][Nom]

Ns	ns[/N|Abbr|Unit]=ns+[Nom]=		[/N|Abbr|Unit][Nom]

NS	ns[/N|Abbr|Unit]=ns+[Nom]=		[/N|Abbr|Unit][Nom]

ns-mal	ns[/N|Abbr|Unit]=ns-+mal[Ins]=mal		[/N|Abbr|Unit][Ins]

(rám)	lparén[Punct]=(+[/N|Pro]=+rá[Subl]=rá+m[1Sg]=m+rpar[Punct]=)		[/N|Pro][Subl][1Sg][Punct]

+hozzá	+ő[Punct]=++[/N|Pro]=+hozzá[All]=hozzá+[3Sg]=		[/N|Pro][All][3Sg]
+hozzá	+[Punct]=++hozzá[/Prev]=hozzá	hozzá	[/Prev]
```

I'm open for suggestions how these lemmas should be handled.

**Comment by dlazesz** [comment]
Final conclusion:

- I have (re)added the obscure tags to emLem config (TODO fix inconsistencies among the codelist, emMorph and emLem)
- Another bug was found and fixed in parsing the output from emMorph (also present in the JAVA version)

These modifications introduce changes in a few words that should be written separately and uncovered a few other bugs, which will be addressed in the future (TODO). See the [commit log](https://github.com/dlt-rilmta/emmorphpy/commit/8d5e682dd1bfcf1031d30e5493bdb2cf12ddcb83) for details.

emtsv was bumped to contain this commit in ebaab93b9ad1cd0f5f4f0d6ee5a91bc1d0b635c0 which fixes this issue.

Thank you for reporting this issue!
